# Generated by Django 2.2 on 2019-07-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autochart', '0003_auto_20190714_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
