# Generated by Django 2.2 on 2019-07-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autochart', '0005_remove_userfile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='session_time',
            field=models.IntegerField(),
        ),
    ]
